### ISSUE TITLE
我测试数学公式时，闪退，请问怎么处理？

### ISSUE THREAD

**Issue by zhouzhuo810** [lidary-byte/HMarkdown#7]
### Markdown内容

```
Latex公式演示
  
$$
c = \sqrt{a^{2}+b_{0}^{2} +e^{x}}
$$  
  
$$
lim[cf(x)]= clim(f(x))
$$  
  
$$
lim[f(x)]^ n=[limf(x)]^n
$$  
  
行内公式$$lim[f(x)]^ n=[limf(x)]^n$$测试  
  

```

### 闪退日志：

```
Device info:emulator
Build info:emulator 5.0.0.65(SP73DEVC00E65R4P11log)
Fingerprint:45892700b0e20673305a2ab27db5834f70194f5a57fd2069bd1f669270597fa2
Version:1.0.0
VersionCode:1
PreInstalled:No
Foreground:Yes
Pid:24754
Uid:20020042
Reason:TypeError
Error name:TypeError
Error message:Cannot read property builder of undefined
Stacktrace:
    at anonymous (Markdown/src/main/ets/MarkdownComponent.ets:56:11)
    at ifElseBranchUpdateFunction (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:4300:1)
    at anonymous (Markdown/src/main/ets/MarkdownComponent.ets:55:16)
    at updateFunc (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6778:1)
    at observeComponentCreation2 (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6819:1)
    at forEachItemGenFunction (Markdown/src/main/ets/MarkdownComponent.ets:24:14)
    at anonymous (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:4385:1)
    at forEachUpdateFunction (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:4372:1)
    at anonymous (Markdown/src/main/ets/MarkdownComponent.ets:57:10)
    at updateFunc (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6778:1)
    at UpdateElement (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6498:1)
    at anonymous (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6721:1)
    at updateDirtyElements (/usr1/hmos_for_system/src/increment/sourcecode/foundation/arkui/ace_engine/frameworks/bridge/declarative_frontend/engine/stateMgmt.js:6716:1)
    at rerender (Markdown/src/main/ets/MarkdownComponent.ets:329:9)
```

**Comment by zhouzhuo810** [comment]
plugin是复制的demo的，没做修改。

**Comment by lidary-byte** [comment]
需要定义一下
```  
markConfig.customBlockBuilder = wrapBuilder(BlockBuilder)
markConfig.customInlineBuilder = wrapBuilder(InlineBuilder)
```

可以看一下EntryAbility.ets这个文件

**Comment by zhouzhuo810** [comment]
> 需要定义一下
> 
> ```
> markConfig.customBlockBuilder = wrapBuilder(BlockBuilder)
> markConfig.customInlineBuilder = wrapBuilder(InlineBuilder)
> ```
> 
> 可以看一下EntryAbility.ets这个文件

好的，我发现了，不过现在没有可用的数学公式svg生成方案，只能放弃了，我现在改用webview+marked.js方案实现。
